//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPHBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public string CUGNo { get; set; }
        public string GCM { get; set; }
        public string IEMEI { get; set; }
    }
}
