//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPHBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;

    public partial class UPHBDContext : DbContext
    {
        public UPHBDContext()
            : base("name=UPHBDContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Directory> Directories { get; set; }
        public DbSet<OfficerLogin> OfficerLogins { get; set; }
        public DbSet<Designation> Designations { get; set; }

        public virtual int spUpdateDirectory(Nullable<int> id, string name, string designation, string cUGNo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));

            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));

            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));

            var cUGNoParameter = cUGNo != null ?
                new ObjectParameter("CUGNo", cUGNo) :
                new ObjectParameter("CUGNo", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateDirectory", idParameter, nameParameter, designationParameter, cUGNoParameter);
        }

        public virtual int spCreateDirectory(Nullable<int> id, string name, string designation, string cUGNo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));

            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));

            var designationParameter = designation != null ?
                new ObjectParameter("Designation", designation) :
                new ObjectParameter("Designation", typeof(string));

            var cUGNoParameter = cUGNo != null ?
                new ObjectParameter("CUGNo", cUGNo) :
                new ObjectParameter("CUGNo", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCreateDirectory", idParameter, nameParameter, designationParameter, cUGNoParameter);
        }
        public virtual int spUpdateGCM(string gCM, string iEMEI, string cUGNo)
        {
            var gCMParameter = gCM != null ?
                new ObjectParameter("GCM", gCM) :
                new ObjectParameter("GCM", typeof(string));

            var iEMEIParameter = iEMEI != null ?
                new ObjectParameter("IEMEI", iEMEI) :
                new ObjectParameter("IEMEI", typeof(string));

            var cUGNoParameter = cUGNo != null ?
                new ObjectParameter("CUGNo", cUGNo) :
                new ObjectParameter("CUGNo", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateGCM", gCMParameter, iEMEIParameter, cUGNoParameter);
        }
    }
}
